Gusto/it-cpe-opensource

autopromote/requirements.txt

Update requirements for autopromote. Both these libraries have vulnerabilities in previous version.

update autopromote requirements

---

autopromote/autopromote.py

Python 3 returns a filter object: https://stackoverflow.com/questions/13638898/how-to-use-filter-map-and-reduce-in-python-3
This update expands our filter to a normal list before we begin processing.

expand filter object before use

---

chef/cookbooks/cpe_activedirectory/recipes/default.rb
chef/cookbooks/cpe_yo/recipes/default.rb
chef/cookbooks/cpe_zoom/recipes/default.rb
chef/cookbooks/cpe_zoom/resources/cpe_zoom.rb

Same as #4 but now GPG-signed, sealed, and delivered:
This PR will move the `return unless node.macos?` guard block into the recipe so the non-macOS clients bail immediately. Also, this pull request will implement platform guards in `cpe_activedirectory` and `cpe_yo`. 
Proposed changes follows suit with the pattern in Facebook. Pinterest, and Uber's open-source cookbooks.

Move `cpe_zoom` platform guard; add guards in `cpe_activedirectory`, `cpe_yo`

---

chef/cookbooks/cpe_activedirectory/README.md
chef/cookbooks/cpe_activedirectory/attributes/default.rb
chef/cookbooks/cpe_activedirectory/resources/cpe_activedirectory.rb

I noticed that the `ruby_block` is not idempotent before merging it internally, so if you are trying to get to 0 resources updated at the end of your run, this makes it impossible.
After thinking through the code, I realized it ultimately falls into ensuring the guard is run at runtime. This greatly reduces it's complexity and functions similarly.
I did drop the warning about `unsupported` keys, because that's not going to be possible with the guard and I think it outweighs the need for someone to just realize this (since it's documented anyway in the attributes file).
This also bails on the `configure` block and warns if it's used in conjunction with installing via profile, since we found out it fails.

refactor configure block and better logging

---

autopkg/autopkg_tools.py

If you look at `result` you can confirm stdout is the output of running git with no args:
```
CompletedProcess(args=['git', 'rev-parse', '--abbrev-ref', 'HEAD'], stdout=b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace- stderr=b'')
```
This patch instead passes args as a string.

Fix git runs in autopkg_tools

---

autopromote/autopromote.py

This PR seeks to respect the promotion days defined for a new package by treating autopkg's `creation_date` as the `last_promoted` date.

use creation_date as last_promoted date on new packages, if possible

---

autopkg/autopkg_tools.py

From a debug run:
```
Running git add pkgs/apps/ZoomIT/ZoomIT-5.2.3 (45131.0907).pkg
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `git add pkgs/apps/ZoomIT/ZoomIT-5.2.3 (45131.0907).pkg'
Running git add pkgsinfo/apps/ZoomIT/ZoomIT-5.2.3 (45131.0907).plist
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `git add pkgsinfo/apps/ZoomIT/ZoomIT-5.2.3 (45131.0907).plist'
```
Whoops!

encapsulate pkg/pkginfo paths in quotes to allow for spaces

---

chef/cookbooks/cpe_activedirectory/resources/cpe_activedirectory.rb
chef/cookbooks/cpe_ublock/resources/cpe_ublock.rb
chef/cookbooks/cpe_yo/resources/cpe_yo.rb

This PR will do one thing: Replace all instances of #Hash.reject { |_k, v | v.nil? } with #Hash.compact.
This has been shown (chef/chef#10601) to increase speed by a reasonable amount and is a bit more simple (IMHO).
Tested this locally with Chef Solo and -- with a sample size of 4x runs -- our run_list went from an average run time of 30s (using .reject) to 24s (using .compact).

Replace #Hash.reject with #Hash.compact

---

chef/cookbooks/cpe_activedirectory/resources/cpe_activedirectory.rb

Chef client v16.1 or 16.2 had a bug whereby one must supply `:os` or it will blow-up Chef runs. Kind of annoying to keep it in there for this minor bug but I don't think there's any harm in doing so.

Bugfix for cpe_ad on specific vers of chef-client

---

autopkg/autopkg_tools.py
autopkg/workflows/autopkg.yml

This adds in recipe verification before handling the recipe. If the verification fails, the recipe run is skipped. The output of the failed `verify-trust-info -vvv` is sent to Slack if configured.
This also adds the ability to manually run a workflow of a single recipe.

Adding recipe verification and ability to run single recipes

---

autopromote/README.md
autopromote/autopromote.py

adding a package name-version into the `denylist` will stop it from being autopromoted #51 
`"denylist": ["Zoom-5.5.12513.0205"]`
```
>>> name = "Zoom"
>>> fullname = "Zoom"
>>> version = "5.5.12513.0205"
>>> allowlist = ["Spotify"]
>>> denylist = ["Zoom-5.5.12513.0205"]
>>> test_matching()
Skipping Zoom-5.5.12513.0205: excluded by denylist
(False, {'plist': {}, 'from': None, 'to': None, 'fullname': 'fullname'})
```
```
>>> name = "Spotify"
>>> version = "1.0.0"
>>> allowlist = ["Spotify"]
>>> denylist = ["Zoom-5.5.12513.0205"]
>>> test_matching()
No skip
```
```
>>> name = "Zoom"
>>> version = "5.5.12513.99999"
>>> denylist = ["Zoom-5.5.12513.0205"]
>>> test_matching()
No skip
```
~Also fixes the bug where a non empty `allowlist` skips all promotions~

Added support for name-version denial

---

chef/cookbooks/cpe_activedirectory/metadata.rb
chef/cookbooks/cpe_activedirectory/resources/cpe_activedirectory.rb

This PR will solve #54 by enabling `unified_mode` (see: https://docs.chef.io/unified_mode) and setting the cookbook's minimum supported Chef client version to v14.14 (the earliest client version that is able to understand `unified_mode`).

Enable `unified_mode` on `cpe_activedirectory`

---

autopkg/autopkg_tools.py
autopkg/workflows/autopkg.yml

Hardcoding `master` as the default branch is causing issues now that Github has changed the default branch name to `main`. A more elegant fix should be done, but for now this works.

Change branch name to main

---

autopromote/README.md
autopromote/autopromote.json
autopromote/autopromote.py
autopromote/requirements.txt

This PR improves the allow and deny lists by turning them into dicts of this structure:
```json
{
"name": "version"
}
```
Where `version` may be null or a regex version. Additionally, the allowlist has been changed - no longer does the allowlist take precedence, instead the allowlist should be used to pin particular versions of a package. For instance, setting
```json
"allowlist": {
"Zoom": "9.*"
}
```
pins Zoom to 9.x versions - only they will be promoted. To blanket deny promotion to a pkg, the denylist can be used with a null value (or "all") for version.
Also in this PR I've replaced deprecated methods called on plistlib and logger.

Improve allow/deny list

---

autopromote/autopromote.json
autopromote/autopromote.py

These proposed changes allow a little more flexibility in the autopromote script. Both changes default to the old behavior, so no changes are required to continue use of the tool.
You can now set an environment variable declaring the location of `autopromote.json`. Inside that file is a new configuration option that controls whether makecatalogs is run during script execution.
Additionally, this makes it possible to output the results to a file instead of only to Slack.

Add config options

---

chef/cookbooks/cpe_activedirectory/README.md
chef/cookbooks/cpe_activedirectory/metadata.rb
chef/cookbooks/cpe_activedirectory/recipes/default.rb
chef/cookbooks/cpe_anyconnect/recipes/default.rb
chef/cookbooks/cpe_anyconnect/resources/cpe_anyconnect.rb
chef/cookbooks/cpe_hot_corners/recipes/default.rb
chef/cookbooks/cpe_notifications/recipes/default.rb
chef/cookbooks/cpe_printers/recipes/default.rb
chef/cookbooks/cpe_profiles_workspaceone/recipes/default.rb
chef/cookbooks/cpe_textexpander/recipes/default.rb
chef/cookbooks/cpe_textexpander/resources/cpe_textexpander.rb
chef/cookbooks/cpe_yo/recipes/default.rb
chef/node_functions/gusto.rb

This PR will replace all instances of `node.windows?`, `node.macos?` with `windows?`, `macos?` (respectively).
I recently noticed that Chef has some native helper functions available (See: below code block) for discerning platform family (i.e. `macos?`, `windows?`, `debian?`, `linux?`, et al) that make the corresponding Facebook's helper node functions moot.
```
$ sudo chef-shell
loading configuration: none (standalone session)
true
Session type: standalone
Loading.................done.
Welcome to the chef-shell 17.7.29
For usage see https://docs.chef.io/chef_shell/
run `help' for help, `exit' or ^D to quit.
chef (17.7.29)> require 'pry'
=> true
chef (17.7.29)> binding.pry
Frame number: 0/14
[1] pry(main)> show-method macos?
From: …
```

Swap-out `node.macos?`, `node.windows?` for `macos?`, `windows?`

---

autopromote/autopromote.py

This change fixes a typo that calls `logging.debug()` directly instead of calling the defined `logger.debug()` method. The typo caused a second, non-configured instance of `logging` to be created and all subsequent messages to be duplicated. The result of this change cleans up the script output and all logging is directed to the defined logger.

Fixed typo that created a second logging instance

---

chef/cookbooks/cpe_activedirectory/README.md
chef/cookbooks/cpe_activedirectory/attributes/default.rb
chef/cookbooks/cpe_activedirectory/resources/cpe_activedirectory.rb

`bind` method runs when `node.default['cpe_activedirectory']['unbind'] = true` is set with `node.default['cpe_activedirectory']['bind'] = true`. this is now fixed
adds `node.default['cpe_activedirectory']['force_unbind'] = true` to not care if the AD domain is reachable.

Don't bind when unbind is true and add force unbind method

---

autopromote/autopromote.py
autopromote/requirements.txt

I noticed that [Slacker was archived](https://github.com/os/slacker/commit/3c7f43f75ee838be1121342c1aea1360388015e8), so I wanted to update this to use the Slack provided Python SDK.

Replace Slacker with Slack Python SDK

---

autopkg/workflows/autopkg.yml

Current GitHub Actions are producing warnings:
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. 
For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Bumping actions/checkout version from 3.0.2 to 3.2.0 fixes these warnings.

bump actions/checkout version from 3.0.2 to 3.2.0

---

autopromote/README.md
autopromote/autopromote.json
autopromote/autopromote.py

:wave: 
Small delta for orgs which do not use force install dates by default.

add enforce_force_install_date parameter

---

autopromote/autopromote.py

After waiting ~22 hours for a package to be promoted on Gusto's ultra-fast (i.e. 0.25) channel, I started digging into why.
[The logs](https://github.com/Gusto/cpe-autopkg-pipeline/actions/runs/8729344734/job/23951120554#step:10:2251) indicate the `gusto_scope` package was not eligible for promotion. This repo is using [this logic](https://github.com/Gusto/it-cpe-opensource/blob/main/autopromote/autopromote.py#L352) to calculate how many days have passed. It uses [the `days` attribute](https://docs.python.org/3/library/datetime.html#datetime.timedelta.resolution), which represents the whole number of days of a time span **excluding any remaining seconds**:
```python
>>> arrow.now() - last_promoted
datetime.timedelta(seconds=78916, microseconds=943201)
>>> (arrow.now() - …
```

Fix sub-day auto promotion
